export const products = [
  { nomFrance: "Baguette complet", nomArabe: "", marque: "CHOPAIN", code: "20400460", bareCode: "", image: "", prix: "3.5", Qte: "" },
  { nomFrance: "Baguette semoule", nomArabe: "", marque: "CHOPAIN", code: "20400461", bareCode: "", image: "", prix: "3.80", Qte: "" },
  { nomFrance: "Pain sandwich complet", nomArabe: "", marque: "CHOPAIN", code: "20400656", bareCode: "", image: "", prix: "2.0", Qte: "" },
  { nomFrance: "Pain sandwich Nature", nomArabe: "", marque: "CHOPAIN", code: "20400657", bareCode: "", image: "", prix: "2.0", Qte: "" },
  { nomFrance: "Pain Rond complet", nomArabe: "", marque: "CHOPAIN", code: "20400464", bareCode: "", image: "", prix: "2.0", Qte: "" },
  { nomFrance: "Pain Rond semoule", nomArabe: "", marque: "CHOPAIN", code: "20400465", bareCode: "", image: "", prix: "2.0", Qte: "" },
  { nomFrance: "Pain chocolat", nomArabe: "", marque: "CHOPAIN", code: "20400466", bareCode: "", image: "", prix: "5.30", Qte: "" },
  { nomFrance: "croissant Beurre", nomArabe: "", marque: "CHOPAIN", code: "20400467", bareCode: "", image: "", prix: "4.5", Qte: "" },
  { nomFrance: "escargot", nomArabe: "", marque: "CHOPAIN", code: "20400468", bareCode: "", image: "", prix: "4.0", Qte: "" },
  { nomFrance: "chausson Pomme", nomArabe: "", marque: "CHOPAIN", code: "20400469", bareCode: "", image: "", prix: "0", Qte: "" },
  { nomFrance: "Grand Palmier", nomArabe: "", marque: "CHOPAIN", code: "20400659", bareCode: "", image: "", prix: "0", Qte: "" },
  { nomFrance: "Pain suisse", nomArabe: "", marque: "CHOPAIN", code: "20400474", bareCode: "", image: "", prix: "5.9", Qte: "" },
  { nomFrance: "cookies Amande", nomArabe: "", marque: "CHOPAIN", code: "20400829", bareCode: "", image: "", prix: "", Qte: "" },
  { nomFrance: "Brownies", nomArabe: "", marque: "CHOPAIN", code: "20400830", bareCode: "", image: "", prix: "", Qte: "" },
  { nomFrance: "escargot legumes", nomArabe: "", marque: "CHOPAIN", code: "20400832", bareCode: "", image: "", prix: "", Qte: "" },
  { nomFrance: "Torsade Olive", nomArabe: "", marque: "CHOPAIN", code: "20400833", bareCode: "", image: "", prix: "", Qte: "" },
  { nomFrance: "croissant Choco-Noisette", nomArabe: "", marque: "CHOPAIN", code: "20400834", bareCode: "", image: "", prix: "", Qte: "" },
  { nomFrance: "Tulipe chocolat", nomArabe: "", marque: "CHOPAIN", code: "20400835", bareCode: "", image: "", prix: "", Qte: "" },
  { nomFrance: "Tulipe caramel", nomArabe: "", marque: "CHOPAIN", code: "20400836", bareCode: "", image: "", prix: "", Qte: "" },
  { nomFrance: "croissant Mangue", nomArabe: "", marque: "CHOPAIN", code: "20400837", bareCode: "", image: "", prix: "", Qte: "" },
  { nomFrance: "Eau de Table", nomArabe: "", marque: "VITALYA", code: "21704398", bareCode: "", prix: "9.90", image: "", Qte: "5.0" },
  { nomFrance: "PACK EAU-MINRA 5l+1", nomArabe: "", marque: "AIN SAISS", code: "21706062", bareCode: "", image: "", prix: "23.90", Qte: "6x2" },
  { nomFrance: "EAU MINERAL 5+1SAISS", nomArabe: "", marque: "AIN SAISS", code: "21704937", bareCode: "", image: "AS5+1.png", prix: "12.80", Qte: "5L+1" },
  { nomFrance: "Eau minérale naturelle", nomArabe: "", marque: "AIN SAISS", code: "20300857", bareCode: "", image: "", prix: "2.50", Qte: "0.5" },
  { nomFrance: "Eau minérale naturelle", nomArabe: "", marque: "AIN SAISS", code: "20300858", bareCode: "", image: "", prix: "4.55", Qte: "1.5" },
  { nomFrance: "Eau minérale naturelle", nomArabe: "", marque: "SIDI ALI", code: "20300011", bareCode: "", image: "SD0.5.png", prix: "2.75", Qte: "0.5" },
  { nomFrance: "Eau minérale naturelle", nomArabe: "", marque: "SIDI ALI", code: "20300010", bareCode: "", image: "", prix: "4.80", Qte: "1.5" },
  { nomFrance: "Eau minérale naturelle", nomArabe: "", marque: "SIDI ALI", code: "20300174", bareCode: "", image: "", prix: "1.70", Qte: "0.33C" },
  { nomFrance: "Eau minérale naturelle", nomArabe: "", marque: "SIDI ALI", code: "20300562", bareCode: "", image: "", prix: "5.50", Qte: "2.0" },
  { nomFrance: "Eau de source naturelle", nomArabe: "", marque: "ACYL", code: "21705244", bareCode: "", image: "", prix: "4.50", Qte: "1.5" },
  { nomFrance: "Eaux de table", nomArabe: "", marque: "BAHIA", code: "20300009", bareCode: "", image: "", prix: "9.95", Qte: "5.0" },
  { nomFrance: "Eau minérale naturelle", nomArabe: "", marque: "AIN ATLAS", code: "20300085", bareCode: "", image: "", prix: "11.70", Qte: "5.0" },
  { nomFrance: "Eau minérale naturelle", nomArabe: "", marque: "AIN IFRANE", code: "21705828", bareCode: "", image: "", prix: "10.90", Qte: "5.0" },
  { nomFrance: "Essuie tout", nomArabe: "", marque: "BLUME", code: "21703996", bareCode: "", image: "", prix: "29.90", Qte: "1kg" },
  { nomFrance: "Diffuseur de parfum", nomArabe: "معطر الجو", marque: "ETEREA REED", code: "21706120", bareCode: "", image: "", prix: "27.90", Qte: "100 ml" }
];

