export const products = [
  { nomFrance: "Baguette complet", nomArabe: "", marque: "CHOPAIN", code: "20400460", bareCode: "", image: "", prix: "3.5", Qte: "" },
  { nomFrance: "Baguette semoule", nomArabe: "", marque: "CHOPAIN", code: "20400461", bareCode: "", image: "", prix: "3.80", Qte: "" },
  { nomFrance: "Pain sandwich complet", nomArabe: "", marque: "CHOPAIN", code: "20400656", bareCode: "", image: "", prix: "2.0", Qte: "" },
  { nomFrance: "Pain sandwich Nature", nomArabe: "", marque: "CHOPAIN", code: "20400657", bareCode: "", image: "", prix: "2.0", Qte: "" },
  { nomFrance: "Pain Rond complet", nomArabe: "", marque: "CHOPAIN", code: "20400464", bareCode: "", image: "", prix: "2.0", Qte: "" },
  { nomFrance: "Pain Rond semoule", nomArabe: "", marque: "CHOPAIN", code: "20400465", bareCode: "", image: "", prix: "2.0", Qte: "" },
  { nomFrance: "Pain chocolat", nomArabe: "", marque: "CHOPAIN", code: "20400466", bareCode: "", image: "", prix: "5.30", Qte: "" },
  { nomFrance: "croissant Beurre", nomArabe: "", marque: "CHOPAIN", code: "20400467", bareCode: "", image: "", prix: "4.5", Qte: "" },
  { nomFrance: "escargot", nomArabe: "", marque: "CHOPAIN", code: "20400468", bareCode: "", image: "", prix: "4.0", Qte: "" },
  { nomFrance: "chausson Pomme", nomArabe: "", marque: "CHOPAIN", code: "20400469", bareCode: "", image: "", prix: "0", Qte: "" },
  { nomFrance: "Grand Palmier", nomArabe: "", marque: "CHOPAIN", code: "20400659", bareCode: "", image: "", prix: "0", Qte: "" },
  { nomFrance: "Pain suisse", nomArabe: "", marque: "CHOPAIN", code: "20400474", bareCode: "", image: "", prix: "5.9", Qte: "" },
  { nomFrance: "cookies Amande", nomArabe: "", marque: "CHOPAIN", code: "20400829", bareCode: "", image: "", prix: "", Qte: "" },
  { nomFrance: "Brownies", nomArabe: "", marque: "CHOPAIN", code: "20400830", bareCode: "", image: "", prix: "", Qte: "" },
  { nomFrance: "escargot legumes", nomArabe: "", marque: "CHOPAIN", code: "20400832", bareCode: "", image: "", prix: "", Qte: "" },
  { nomFrance: "Torsade Olive", nomArabe: "", marque: "CHOPAIN", code: "20400833", bareCode: "", image: "", prix: "", Qte: "" },
  { nomFrance: "croissant Choco-Noisette", nomArabe: "", marque: "CHOPAIN", code: "20400834", bareCode: "", image: "", prix: "", Qte: "" },
  { nomFrance: "Tulipe chocolat", nomArabe: "", marque: "CHOPAIN", code: "20400835", bareCode: "", image: "", prix: "", Qte: "" },
  { nomFrance: "Tulipe caramel", nomArabe: "", marque: "CHOPAIN", code: "20400836", bareCode: "", image: "", prix: "", Qte: "" },
  { nomFrance: "croissant Mangue", nomArabe: "", marque: "CHOPAIN", code: "20400837", bareCode: "", image: "", prix: "", Qte: "" },
  { nomFrance: "Eau de Table", nomArabe: "", marque: "VITALYA", code: "21704398", bareCode: "", prix: "9.90", image: "./images/vitalya 5L.PNG", Qte: "5.0" },
  { nomFrance: "PACK EAU-MINRA 5l+1", nomArabe: "", marque: "AIN SAISS", code: "21706062", bareCode: "", image: "./images/pack ain saiss 5L+1.PNG", prix: "23.90", Qte: "6x2" },
  { nomFrance: "EAU MINERAL 5+1SAISS", nomArabe: "", marque: "AIN SAISS", code: "21704937", bareCode: "", image: "./images/AS5+1.png", prix: "12.80", Qte: "5L+1" },
  { nomFrance: "Eau minérale naturelle", nomArabe: "", marque: "AIN SAISS", code: "20300857", bareCode: "", image: "./images/ain sais 0.5L.PNG", prix: "2.50", Qte: "0.5" },
  { nomFrance: "Eau minérale naturelle", nomArabe: "", marque: "AIN SAISS", code: "20300858", bareCode: "", image: "./images/ain sais 1.5L.PNG", prix: "4.55", Qte: "1.5" },
  { nomFrance: "Eau minérale naturelle", nomArabe: "", marque: "SIDI ALI", code: "20300011", bareCode: "", image: "./images/SD0.5.png", prix: "2.75", Qte: "0.5" },
  { nomFrance: "Eau minérale naturelle", nomArabe: "", marque: "SIDI ALI", code: "20300010", bareCode: "", image: "./images/SD 1.5L.PNG", prix: "4.80", Qte: "1.5" },
  { nomFrance: "Eau minérale naturelle", nomArabe: "", marque: "SIDI ALI", code: "20300174", bareCode: "", image: "./images/SD 0.33L.PNG", prix: "1.70", Qte: "0.33C" },
  { nomFrance: "Eau minérale naturelle", nomArabe: "", marque: "SIDI ALI", code: "20300562", bareCode: "", image: "./images/SD 2L.PNG", prix: "5.50", Qte: "2.0" },
  { nomFrance: "Eau de source naturelle", nomArabe: "", marque: "ACYL", code: "21705244", bareCode: "", image: "./images/acyl 1.5L .PNG", prix: "4.50", Qte: "1.5" },
  { nomFrance: "Eaux de table", nomArabe: "", marque: "BAHIA", code: "20300009", bareCode: "", image: "./images/bahia 5L.PNG", prix: "9.95", Qte: "5.0" },
  { nomFrance: "Eau minérale naturelle", nomArabe: "", marque: "AIN ATLAS", code: "20300085", bareCode: "", image: "./images/ain atlas 5L.PNG", prix: "11.70", Qte: "5.0" },
  { nomFrance: "Eau minérale naturelle", nomArabe: "", marque: "AIN IFRANE", code: "21705828", bareCode: "", image: "./images/ain ifrane 5L.PNG", prix: "10.90", Qte: "5.0" },
  { nomFrance: "Diffuseur de parfum", nomArabe: "معطر الجو", marque: "ETEREA REED", code: "21706120", bareCode: "", image: "./images/ETEREA REED difuseur de parfum.PNG", prix: "27.90", Qte: "100 ml" },
  {nomFrance: "Vermicelle de chine", nomArabe: "شعرية صينية", marque: "LONGKOU", code: "21706197", bareCode: "", image: "./images/Vermicelle de chine_LONGKOU.PNG", prix: "", Qte: "200"},
  {nomFrance: "Nouilles instantanées", nomArabe: "نودلز سريعة التحضير", marque: "HARMONY", code: "21705208", bareCode: "", image: "./images/Nouilles instantanées_HARMONY.PNG", prix: "", Qte: "400"},
  {nomFrance: "Essuie tout", nomArabe: "مناشف ورقية", marque: "BLUME", code: "21703996", bareCode: "", image: "./images/MEGA HAVLU.PNG", prix: "", Qte: "1"},
  {nomFrance: "Oignon émincé", nomArabe: "بصل مفروم مجفف", marque: "PEPERONI", code: "21706298", bareCode: "", image: "", prix: "./images/Oignon émincé.PNG", Qte: "90"},
  {nomFrance: "Sauce piquante", nomArabe: "صلصة حارة", marque: "YURI", code: "21705173", bareCode: "", image: "./images/Sauce piquante yuri.PNG", prix: "4.90", Qte: "88"},
  {nomFrance: "Cake", nomArabe: "كيك", marque: "MANDUL", code: "21705921", bareCode: "", image: "./images/cake mandul.PNG", prix: "", Qte: "200"},
  {nomFrance: "Infusion eart grey", nomArabe: "شاي بالأعشاب", marque: "AHMAD TEA", code: "21705750", bareCode: "", image: "./images/infusion eart grey.PNG", prix: "", Qte: "20U"},
  {nomFrance: "Infusion blackcurrant burst", nomArabe: "شاي بالأعشاب", marque: "AHMAD TEA", code: "21705751", bareCode: "", image: "./images/infusion blackcurrant burst.PNG", prix: "", Qte: "20unite"},
  {nomFrance: "Biscuit", nomArabe: "بسكويت", marque: "HAYHAY", code: "21705811", bareCode: "", image: "./images/hayhay bimo.PNG", prix: "", Qte: "100"},
  {nomFrance: "SAVON LIQUIDE", nomArabe: "الصابون السائل", marque: "IŞIL", code: "21401674", bareCode: "", image:"./images/savon isil 750ml.PNG", prix: "", Qte: "750"},
  {nomFrance: "Snack de maïs", nomArabe: "مقبلات", marque: "SPIDERS TOSFRIT", code: "21705795", bareCode: "", image: "./images/Spiders pop.PNG", prix: "", Qte: "90"},
  {nomFrance: "Pop corn", nomArabe: "فشار", marque: "SOHO", code: "21705792", bareCode: "", image: "./images/wild pop.PNG", prix: "", Qte: "70"},
  {nomFrance: "Désodorisant parfumé", nomArabe: "معطر الجو", marque: "RELEVI", code: "21704541", bareCode: "", image: "./images/désodorisant parfumé.PNG", prix: "14.90", Qte: "3U"},
  {nomFrance: "Trio de poulet panés", nomArabe: "", marque: "CRANCHITTA", code: "21702761", bareCode: "", image: "./images/trio de poulet panés.PNG", prix: "29.90", Qte: "300"},
  {nomFrance: "pyjama flannel pour homme ", nomArabe: "", marque: "", code: "21609719", bareCode: "", image: "./images/pyjama flanel pour homme.PNG", prix: "119.90", Qte: "M/L/XL/XXL"},
  {nomFrance: "pyjama flannel pour garçon ", nomArabe: "", marque: "", code: "21609720", bareCode: "", image: "./images/pyjama flannel pour garçonPNG.PNG", prix: "89.90", Qte: "5-6/7-8/9-10/11-12"},
  {nomFrance: "pack de 2 slip femmes bateau", nomArabe: "", marque: "COMFORT FAMILY", code: "21501137", bareCode: "", image: "", prix: "29.90", Qte: "L/XL"},
  {nomFrance: "pack de 2 slip femmes bateau", nomArabe: "", marque: "COMFORT FAMILY", code: "21501136", bareCode: "", image: "./images/", prix: "29.90", Qte: "S/M"},
  {nomFrance: "slips femme 3PCS", nomArabe: "", marque: "COMFORT FAMILY", code: "21501128", bareCode: "", image: "./images/", prix: "39.90", Qte: "L/XL"},
  {nomFrance: "slips femme 3PCS", nomArabe: "", marque: "COMFORT FAMILY", code: "21501132", bareCode: "", image: "./images/", prix: "39.90", Qte: "S/M"},
  {nomFrance: "Boxer hommes 1PCS", nomArabe: "", marque: "COMFORT FAMILY", code: "21501130", bareCode: "", image: "./images/", prix: "29.90", Qte: "S/M"},
  {nomFrance: "Boxer hommes 1PCS", nomArabe: "", marque: "COMFORT FAMILY", code: "21501127", bareCode: "", image: "./images/", prix: "29.90", Qte: "L/XL"},
  {nomFrance: "debard femme 1PCS", nomArabe: "", marque: "COMFORT FAMILY", code: "21501134", bareCode: "", image: "./images/", prix: "29.90", Qte: "S/M MIX"},
  {nomFrance: "debard homme 1PCS", nomArabe: "", marque: "COMFORT FAMILY", code: "21501124", bareCode: "", image: "./images/", prix: "29.90", Qte: "L/XL"},
  {nomFrance: "debard homme 1PCS", nomArabe: "", marque: "COMFORT FAMILY", code: "21501131", bareCode: "", image: "./images/", prix: "29.90", Qte: "S/M"},
  {nomFrance: "deo stick homme", nomArabe: "", marque: "NARTA", code: "21400625", bareCode: "", image: "./images/narta homme.PNG", prix: "34.90", Qte: ""},
  {nomFrance: "deo stick femme", nomArabe: "", marque: "NARTA", code: "21400945", bareCode: "", image: "./images/narta femme.PNG", prix: "34.90", Qte: ""},
  {nomFrance: "liquide de rinçage", nomArabe: "", marque: "ASPEROX SPARX", code: "21706199", bareCode: "", image: "./images/liquide de rinçage sparx.PNG", prix: "19.90", Qte:"400"},
  {nomFrance: "lait d'amande UHT", nomArabe: "", marque: "BREEZE", code: "21703511", bareCode: "", image: "./images/lait damande uht.PNG", prix: "23.90", Qte:"1"},
  {nomFrance: "Lait hydratant oil corps", nomArabe: "", marque: "VASELINE", code: "21705981", bareCode: "", image: "./images/vaseline 200ml.PNG", prix: "99.90", Qte:"200"},
  {nomFrance: "Boisson", nomArabe: "", marque: "PRIME", code: "21704977", bareCode: "", image: "./images/prime boisson.PNG", prix: "33.50", Qte:"500"},
  {nomFrance: "Pâte chat", nomArabe: "", marque: "TOP PET", code: "21706386", bareCode: "", image: "./images/pate chat.PNG", prix: "8.90", Qte:"415"},
  {nomFrance: "Bol capacite", nomArabe: "", marque: "BAGER", code: "21607739", bareCode: "", image: "./images/bol 1200.PNG", prix: "4.90", Qte:"1200"},
  {nomFrance: "Sucettes", nomArabe: "", marque: "YOUPI-MICHOC", code: "21705862", bareCode: "", image: "./images/youpi-michoc.PNG", prix: "3.50", Qte:"10PCS"},
  {nomFrance: "chocolat mix classic", nomArabe: "", marque: "TOREN", code: "20701960", bareCode: "", image: "./images/toren rouge.PNG", prix: "2.90", Qte:"42"},
  {nomFrance: "chocolat mix classic", nomArabe: "", marque: "TOREN", code: "20701132", bareCode: "", image: "./images/toren rouge.PNG", prix: "2.90", Qte:"42"},
  {nomFrance: "Netoyant anti-rouille et calcaire", nomArabe: "", marque: "AKS", code: "21200691", bareCode: "", image: "./images/aks anti-rouille.PNG", prix: "16.90", Qte:"1000"},
  {nomFrance: "Netoyant multi-usages", nomArabe: "", marque: "AKS", code: "21200690", bareCode: "", image: "./images/aks multi-usages.PNG", prix: "16.90", Qte:"1000"},
  {nomFrance: "Lingette", nomArabe: "", marque: "IVORY", code: "21300466", bareCode: "", image: "./images/lingette ivory.PNG", prix: "2.50", Qte:"15PCS"},
  {nomFrance: "Pate de chat", nomArabe: "", marque: "MICHO", code: "21500999", bareCode: "", image: "./images/pate de chat 100g.PNG", prix: "5.50", Qte:"100"},
  {nomFrance: "gants latex differents tailles", nomArabe: "", marque: "MR GREEN", code: "21500461", bareCode: "", image: "./images/gants latex mr green.PNG", prix: "12.90", Qte:"1PCS"},
  {nomFrance: "bain de bouche mixte", nomArabe: "", marque: "LISTERINE", code: "21401496", bareCode: "", image: "./images/listerine bain bouche.PNG", prix: "34.90", Qte:"250"},
  {nomFrance: "Essuie tout", nomArabe: "", marque: "RENOVA", code: "21706480", bareCode: "", image: "./images/renova esui tout.PNG", prix: "23.90", Qte:"2PCS"},
  {nomFrance: "Jouet interactif pour enfant growing egg", nomArabe: "", marque: "TURTLE", code: "21610130", bareCode: "", image:"./images/jouet interactif enfant egg.PNG", prix: "12.90", Qte:"36"},
  {nomFrance: "Dattes Zahdi", nomArabe: "", marque: "ALBARARI", code: "20500376", bareCode: "", image: "./images/dattes zahdi.PNG", prix: "14.90", Qte:"500"},
  {nomFrance: "Totas chips mix 30g", nomArabe: "", marque: "TOTAS", code: "20500467", bareCode: "", image: "./images", prix: "3.90", Qte:"30"},
  {nomFrance: "dessert mix", nomArabe: "", marque: "LIEGOG", code: "20201065", bareCode: "", image: "./images", prix: "6.90", Qte:"200"},
  {nomFrance: "lot de 3 boites a mouchoires", nomArabe: "", marque: "CASA", code: "21706479", bareCode: "", image: "./images/mouchoires casa.PNG", prix: "22.90", Qte:"3x600PCS"},
  {nomFrance: "Gaufrettes mixte", nomArabe: "", marque: "POKER", code: "20702021", bareCode: "", image: "./images", prix: "3.50", Qte:"45"},
  {nomFrance: "Petit Pois Casses", nomArabe: "", marque: "L'MEMA", code: "20400852", bareCode: "", image: "./images", prix: "9.50", Qte:"500"},
  {nomFrance: "Feves Casses", nomArabe: "", marque: "L'MEMA", code: "20400854", bareCode: "", image: "./images", prix: "8.90", Qte:"500"},
  {nomFrance: "sabot tendance hommes", nomArabe: "", marque: "ORIES", code: "21609530", bareCode: "", image: "./images/sabot ories homme.PNG", prix: "69.90", Qte:"40-45"},
  {nomFrance: "sabot tendance femmes", nomArabe: "", marque: "ORIES", code: "21609528", bareCode: "", image: "./images/sabot ories femme.PNG", prix: "49.90", Qte:"36-41"},
  {nomFrance: "Nectar Mix 330ml", nomArabe: "", marque: "SANTAL", code: "21706373", bareCode: "", image: "./images/santal 330ml.PNG", prix: "7.90", Qte:"330"},
  {nomFrance: "boulettes de sardine 125g", nomArabe: "", marque: "CARLE", code: "21706560", bareCode: "", image: "./images/", prix: "6.95", Qte:"125"},
  {nomFrance: "epices tacos", nomArabe: "", marque: "PEPIRONI", code: "21704783", bareCode: "", image: "./images/epices pepironi tacos.PNG", prix: "7.50", Qte:"38"}







];

